stages:
  - setup

setup:
  stage: setup
  image: ubuntu:latest
  before_script:
    - apt-get update -y
    - apt-get install -y python3 python3-pip python3-venv
    - apt-get install -y ansible
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install jinjanator
  script:
    - python3 --version
    - pip3 --version
    - ansible --version
    - pip list
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - |
      if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
        echo "Main branch..."
        export remote_addr="$REMOTE_ADDRESS" 
        export ansible_user="root" 
        echo "$SSH_PRIVKEY" > private_key.pem
      else
        echo "Development branch..."
        export remote_addr="$REMOTE_DEV_ADDRESS" 
        export ansible_user="root" 
        echo "$SSH_DEV_PRIVKEY" > private_key.pem
      fi
    - chmod 600 private_key.pem
    - jinjanate hosts.ini.j2 > hosts.ini
    - ansible-playbook -i hosts.ini playbook.yml
